MICRO-94: fix eslint config error
Error: .eslintrc:
        Configuration for rule "ts-expect-error" is invalid:
        Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"allow-with-description"').

With current config when not supplying description:
Include a description after the "@ts-expect-error" directive to explain why the @ts-expect-error is necessary. The description must be 3 characters or longer  @typescript-eslint/ban-ts-comment